### ISSUE TITLE
2. küsüre kadar backward compatibility eklenmesi

### ISSUE THREAD

**Issue by elifkus** [istanbulhs/istanbul-hackerspace-app#1]

**Comment by elifkus** [comment]
Uygulama v2.2'den itibaren calisacak hale getirildi. 

2.2'lik bir emulatorde test ettim ama biraz daha test etmek lazim.

**Comment by elifkus** [comment]
2.3 telefonda test ettik. Haritada patladı. 
Hataya bakmamız gerekiyor.

**Comment by elifkus** [comment]
Halil tekrar bakti. Haritada patlamiyor ama  hatitanin arkasindan menuye girince o unlu siyah kare cikiyor.

**Comment by tasomaniac** [comment]
O siyah kare ne yazik ki gitmeyecek. Birkac cozum var hack gibi ama tam olarak cozmuyor sanirim. Sadece bunun icin engellememek lazim bence. Ben son versiyonda 2.3 e kadar destek koydum. Cokme gibi bir sorun yok. Upload etmedim daha. Geri cekeyim mi? Yoksa bu issue yu kapatalim mi?
