### ISSUE TITLE
Tabletle çalışır hale getirilmesi

### ISSUE THREAD

**Issue by elifkus** [istanbulhs/istanbul-hackerspace-app#2]

**Comment by elifkus** [comment]
Developer console'da yapılması gerekenler yazıyormuş. 
![screen shot 2013-05-01 at 19 33 01](https://f.cloud.github.com/assets/890640/449767/291049fa-b27d-11e2-84e4-c5fffd4e0da2.png)

**Comment by CanburakTumer** [comment]
Gereksinimleri sağlayacak şekilde geliştirme tamamlandı. Android markette yayınlanmaya hazır.

**Comment by elifkus** [comment]
Test sırasında haritadan menüye geriye dönünce, menünün üstünde siyah bir kare çıkıyor. 

Ne yazık ki çözümü o kadar kolay değil. Sebebi Map v.2'deki bir bug. Hackathon'da da Orhan uğraşmıştı bayağı. 

SlidingMenu'deki bug raporu:
https://github.com/jfeinstein10/SlidingMenu/issues/228

Google Map v.2'deki bug raporu:
https://code.google.com/p/gmaps-api-issues/issues/detail?id=4659

O bug'da geçen stackoverflow sorusu:
http://stackoverflow.com/questions/13793483/google-maps-android-api-v2-blacking-out-part-of-layout

Bug raporlarında bahsedilen şeyleri deneyebiliriz. Bazıları işe yaramış diyor. Bazıları hiçbiri işe yaparamıyor diyor.

**Comment by CanburakTumer** [comment]
Akşam ilgileneceğim. Ancak emulator'de problemi yaşamıyorum, size göndersem test etme imkanınız olur mu tablet üzerinde?

**Comment by elifkus** [comment]
Tabi test ederiz
