### ISSUE TITLE
Open source lisans eklenmesi

### ISSUE THREAD

**Issue by elifkus** [istanbulhs/istanbul-hackerspace-app#9]
Apache 2.0 olabilir. 

Özetle,
Ticari projede kod kapanabiliyor. 
Proje kullanımından bilgisiayara zarar gelirse sorumluluk kabul etmiyoruz. Projeyi alıp değiştirip kullanınca geliştiricilerin adı kullanılamıyor.

**Comment by tasomaniac** [comment]
Direk Apache 2.0 ekleyelim derim ben. Ekleyeyim mi direk?

**Comment by halilkaya** [comment]
Apache 2.0 olabilir.  Bu arada uygulamanýn arayüzünde güzelleþtirmeler
yapalým diyorum.

**Comment by tasomaniac** [comment]
NavigationDrawer kesinlikle eklenmeli bence sol menu olarak. O buyuk bir
gelisme olur.
Daha sonra baska guzellestirmeler de yapariz.
Apache 2.0 License koyuyorum ben o zaman.

2014-03-17 11:10 GMT+02:00 Halil Kaya notifications@github.com:

> Apache 2.0 olabilir. Bu arada uygulamanýn arayüzünde güzelleþtirmeler
> yapalým diyorum.
> On 17 Mar 2014 11:08, "Said Tahsin Dane" notifications@github.com
> wrote:
> 
> > Direk Apache 2.0 ekleyelim derim ben. Ekleyeyim mi direk?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/istanbulhs/istanbul-hackerspace-app/issues/9#issuecomment-37795744>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/istanbulhs/istanbul-hackerspace-app/issues/9#issuecomment-37795858
> .

## 

Said Tahsin Dane

Lead Mobile Developer, Metrekare.com

tasomaniac.com http://blog.tasomaniac.com/

metrekare.com http://www.metrekare.com/ | iPhone
Apphttp://app.adjust.io/52edzz
 | Android App http://app.adjust.io/1tl52j
